/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorList,
    ErrorListFromJSON,
    ErrorListToJSON,
    JwtObject,
    JwtObjectFromJSON,
    JwtObjectToJSON,
} from '../models';

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Create an API token in the form of a JWT.
     */
    async authenticationJwtPostRaw(): Promise<runtime.ApiResponse<JwtObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/authentication/jwt`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtObjectFromJSON(jsonValue));
    }

    /**
     * Create an API token in the form of a JWT.
     */
    async authenticationJwtPost(): Promise<JwtObject> {
        const response = await this.authenticationJwtPostRaw();
        return await response.value();
    }

}
