/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorList,
    ErrorListFromJSON,
    ErrorListToJSON,
    ServerInfo,
    ServerInfoFromJSON,
    ServerInfoToJSON,
} from '../models';

/**
 * 
 */
export class InfoApi extends runtime.BaseAPI {

    /**
     */
    async getInfoRaw(): Promise<runtime.ApiResponse<ServerInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerInfoFromJSON(jsonValue));
    }

    /**
     */
    async getInfo(): Promise<ServerInfo> {
        const response = await this.getInfoRaw();
        return await response.value();
    }

}
