/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentSessionAssignment
 */
export interface AgentSessionAssignment {
    /**
     * 
     * @type {string}
     * @memberof AgentSessionAssignment
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionAssignment
     */
    readonly agentId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentSessionAssignment
     */
    monitorIds: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof AgentSessionAssignment
     */
    lastHeartbeatTimestamp?: number;
}

export function AgentSessionAssignmentFromJSON(json: any): AgentSessionAssignment {
    return AgentSessionAssignmentFromJSONTyped(json, false);
}

export function AgentSessionAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSessionAssignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'agentId': json['agentId'],
        'monitorIds': json['monitorIds'],
        'lastHeartbeatTimestamp': !exists(json, 'lastHeartbeatTimestamp') ? undefined : json['lastHeartbeatTimestamp'],
    };
}

export function AgentSessionAssignmentToJSON(value?: AgentSessionAssignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sessionId': value.sessionId,
        'monitorIds': value.monitorIds,
        'lastHeartbeatTimestamp': value.lastHeartbeatTimestamp,
    };
}


