/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Agent
 */
export interface Agent {
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    name: string;
    /**
     * Describes what this agent is or where it will run.
     * @type {string}
     * @memberof Agent
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    readonly apiKey?: string;
}

export function AgentFromJSON(json: any): Agent {
    return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        'apiKey': !exists(json, 'apiKey') ? undefined : json['apiKey'],
    };
}

export function AgentToJSON(value?: Agent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'group': value.group,
    };
}


