/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgentSessionAssignment,
    AgentSessionAssignmentFromJSON,
    AgentSessionAssignmentFromJSONTyped,
    AgentSessionAssignmentToJSON,
} from './';

/**
 * 
 * @export
 * @interface AgentSessionState
 */
export interface AgentSessionState {
    /**
     * 
     * @type {string}
     * @memberof AgentSessionState
     */
    group: string;
    /**
     * 
     * @type {Array<AgentSessionAssignment>}
     * @memberof AgentSessionState
     */
    agents?: Array<AgentSessionAssignment>;
}

export function AgentSessionStateFromJSON(json: any): AgentSessionState {
    return AgentSessionStateFromJSONTyped(json, false);
}

export function AgentSessionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSessionState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': json['group'],
        'agents': !exists(json, 'agents') ? undefined : ((json['agents'] as Array<any>).map(AgentSessionAssignmentFromJSON)),
    };
}

export function AgentSessionStateToJSON(value?: AgentSessionState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': value.group,
        'agents': value.agents === undefined ? undefined : ((value.agents as Array<any>).map(AgentSessionAssignmentToJSON)),
    };
}


