/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EmailAlertBody,
    MsTeamsAlertBody,
    WebhookAlertBody,
    EmailAlertBodyFromJSONTyped,
    EmailAlertBodyToJSON,
    MsTeamsAlertBodyFromJSONTyped,
    MsTeamsAlertBodyToJSON,
    WebhookAlertBodyFromJSONTyped,
    WebhookAlertBodyToJSON,
} from './';

/**
 * @type AlertBody
 * 
 * @export
 */
export type AlertBody = EmailAlertBody | MsTeamsAlertBody | WebhookAlertBody;

export function AlertBodyFromJSON(json: any): AlertBody {
    return AlertBodyFromJSONTyped(json, false);
}

export function AlertBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...EmailAlertBodyFromJSONTyped(json, true), ...MsTeamsAlertBodyFromJSONTyped(json, true), ...WebhookAlertBodyFromJSONTyped(json, true) };
}

export function AlertBodyToJSON(value?: AlertBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...EmailAlertBodyToJSON(value), ...MsTeamsAlertBodyToJSON(value), ...WebhookAlertBodyToJSON(value) };
}

