/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Alert,
    AlertFromJSON,
    AlertFromJSONTyped,
    AlertToJSON,
} from './';

/**
 * 
 * @export
 * @interface AlertArray
 */
export interface AlertArray {
    /**
     * 
     * @type {Array<Alert>}
     * @memberof AlertArray
     */
    alerts: Array<Alert>;
}

export function AlertArrayFromJSON(json: any): AlertArray {
    return AlertArrayFromJSONTyped(json, false);
}

export function AlertArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alerts': ((json['alerts'] as Array<any>).map(AlertFromJSON)),
    };
}

export function AlertArrayToJSON(value?: AlertArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alerts': ((value.alerts as Array<any>).map(AlertToJSON)),
    };
}


