/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ConstExpr,
    DivExpr,
    FieldExpr,
    MulExpr,
    PlusExpr,
    SubExpr,
    ConstExprFromJSONTyped,
    ConstExprToJSON,
    DivExprFromJSONTyped,
    DivExprToJSON,
    FieldExprFromJSONTyped,
    FieldExprToJSON,
    MulExprFromJSONTyped,
    MulExprToJSON,
    PlusExprFromJSONTyped,
    PlusExprToJSON,
    SubExprFromJSONTyped,
    SubExprToJSON,
} from './';

/**
 * @type ArthExpr
 * 
 * @export
 */
export type ArthExpr = ConstExpr | DivExpr | FieldExpr | MulExpr | PlusExpr | SubExpr;

export function ArthExprFromJSON(json: any): ArthExpr {
    return ArthExprFromJSONTyped(json, false);
}

export function ArthExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArthExpr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ConstExprFromJSONTyped(json, true), ...DivExprFromJSONTyped(json, true), ...FieldExprFromJSONTyped(json, true), ...MulExprFromJSONTyped(json, true), ...PlusExprFromJSONTyped(json, true), ...SubExprFromJSONTyped(json, true) };
}

export function ArthExprToJSON(value?: ArthExpr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...ConstExprToJSON(value), ...DivExprToJSON(value), ...FieldExprToJSON(value), ...MulExprToJSON(value), ...PlusExprToJSON(value), ...SubExprToJSON(value) };
}

