/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Balance,
    BalanceFromJSON,
    BalanceFromJSONTyped,
    BalanceToJSON,
} from './';

/**
 * 
 * @export
 * @interface Balances
 */
export interface Balances {
    /**
     * 
     * @type {Array<Balance>}
     * @memberof Balances
     */
    balances?: Array<Balance>;
}

export function BalancesFromJSON(json: any): Balances {
    return BalancesFromJSONTyped(json, false);
}

export function BalancesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Balances {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balances': !exists(json, 'balances') ? undefined : ((json['balances'] as Array<any>).map(BalanceFromJSON)),
    };
}

export function BalancesToJSON(value?: Balances | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balances': value.balances === undefined ? undefined : ((value.balances as Array<any>).map(BalanceToJSON)),
    };
}


