/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AndExpr,
    EqExpr,
    GtEqExpr,
    GtExpr,
    LtEqExpr,
    LtExpr,
    NotExpr,
    OrExpr,
    AndExprFromJSONTyped,
    AndExprToJSON,
    EqExprFromJSONTyped,
    EqExprToJSON,
    GtEqExprFromJSONTyped,
    GtEqExprToJSON,
    GtExprFromJSONTyped,
    GtExprToJSON,
    LtEqExprFromJSONTyped,
    LtEqExprToJSON,
    LtExprFromJSONTyped,
    LtExprToJSON,
    NotExprFromJSONTyped,
    NotExprToJSON,
    OrExprFromJSONTyped,
    OrExprToJSON,
} from './';

/**
 * @type BoolExpr
 * 
 * @export
 */
export type BoolExpr = ;

export function BoolExprFromJSON(json: any): BoolExpr {
    return BoolExprFromJSONTyped(json, false);
}

export function BoolExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoolExpr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['exprType']) {
        default:
            throw new Error(`No variant of BoolExpr exists with 'exprType=${json['exprType']}'`);
    }
}

export function BoolExprToJSON(value?: BoolExpr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['exprType']) {
        default:
            throw new Error(`No variant of BoolExpr exists with 'exprType=${value['exprType']}'`);
    }
}

