/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ChargeType {
    Daily = 'daily',
    Weekly = 'weekly',
    Monthly = 'monthly'
}

export function ChargeTypeFromJSON(json: any): ChargeType {
    return ChargeTypeFromJSONTyped(json, false);
}

export function ChargeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeType {
    return json as ChargeType;
}

export function ChargeTypeToJSON(value?: ChargeType | null): any {
    return value as any;
}

