/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ChargeType {
    Daily = 'daily',
    Weekly = 'weekly',
    Monthly = 'monthly'
}

export function ChargeTypeFromJSON(json: any): ChargeType {
    return ChargeTypeFromJSONTyped(json, false);
}

export function ChargeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeType {
    return json as ChargeType;
}

export function ChargeTypeToJSON(value?: ChargeType | null): any {
    return value as any;
}

