/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CmpOperator {
    Eq = 'eq',
    Lt = 'lt',
    Le = 'le',
    Gt = 'gt',
    Ge = 'ge',
    Ne = 'ne'
}

export function CmpOperatorFromJSON(json: any): CmpOperator {
    return CmpOperatorFromJSONTyped(json, false);
}

export function CmpOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CmpOperator {
    return json as CmpOperator;
}

export function CmpOperatorToJSON(value?: CmpOperator | null): any {
    return value as any;
}

