/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResponseError,
    ResponseErrorFromJSON,
    ResponseErrorFromJSONTyped,
    ResponseErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorList
 */
export interface ErrorList {
    /**
     * 
     * @type {Array<ResponseError>}
     * @memberof ErrorList
     */
    errors: Array<ResponseError>;
}

export function ErrorListFromJSON(json: any): ErrorList {
    return ErrorListFromJSONTyped(json, false);
}

export function ErrorListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorFromJSON)),
    };
}

export function ErrorListToJSON(value?: ErrorList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': ((value.errors as Array<any>).map(ResponseErrorToJSON)),
    };
}


