/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Global error code that indicates what went wrong
 * @export
 * @enum {string}
 */
export enum ErrorCode {
    Unauthorised = 'unauthorised',
    Forbidden = 'forbidden',
    NotFound = 'not_found',
    ProductLimitReached = 'product_limit_reached',
    DatabaseFailure = 'database_failure',
    SolutionIncorrect = 'solution_incorrect',
    SolutionExpired = 'solution_expired',
    InternalParseFailure = 'internal_parse_failure',
    InvalidString = 'invalid_string',
    InvalidConfirmationCode = 'invalid_confirmation_code',
    Conflict = 'conflict'
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

