/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArthExpr,
    ArthExprFromJSON,
    ArthExprFromJSONTyped,
    ArthExprToJSON,
} from './';

/**
 * 
 * @export
 * @interface GtExpr
 */
export interface GtExpr {
    /**
     * 
     * @type {ArthExpr}
     * @memberof GtExpr
     */
    lhs: ArthExpr;
    /**
     * 
     * @type {ArthExpr}
     * @memberof GtExpr
     */
    rhs: ArthExpr;
}

export function GtExprFromJSON(json: any): GtExpr {
    return GtExprFromJSONTyped(json, false);
}

export function GtExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): GtExpr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lhs': ArthExprFromJSON(json['lhs']),
        'rhs': ArthExprFromJSON(json['rhs']),
    };
}

export function GtExprToJSON(value?: GtExpr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lhs': ArthExprToJSON(value.lhs),
        'rhs': ArthExprToJSON(value.rhs),
    };
}


