/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtObject
 */
export interface JwtObject {
    /**
     * The JSON Web Token that can be used to access the API.
     * @type {string}
     * @memberof JwtObject
     */
    jwt: string;
    /**
     * Time at which the JWT expires in seconds since Unix Epoc
     * @type {number}
     * @memberof JwtObject
     */
    jwtExpiry: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof JwtObject
     */
    jwtScopes: Array<string>;
    /**
     * A Bearer token that can used to get a new JWT.
     * @type {string}
     * @memberof JwtObject
     */
    refreshToken: string;
    /**
     * Time at which the refresh token expires in seconds since Unix Epoc
     * @type {number}
     * @memberof JwtObject
     */
    refreshTokenExpiry: number;
}

export function JwtObjectFromJSON(json: any): JwtObject {
    return JwtObjectFromJSONTyped(json, false);
}

export function JwtObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jwt': json['jwt'],
        'jwtExpiry': json['jwtExpiry'],
        'jwtScopes': json['jwtScopes'],
        'refreshToken': json['refreshToken'],
        'refreshTokenExpiry': json['refreshTokenExpiry'],
    };
}

export function JwtObjectToJSON(value?: JwtObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jwt': value.jwt,
        'jwtExpiry': value.jwtExpiry,
        'jwtScopes': value.jwtScopes,
        'refreshToken': value.refreshToken,
        'refreshTokenExpiry': value.refreshTokenExpiry,
    };
}


