/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Monitor,
    MonitorFromJSON,
    MonitorFromJSONTyped,
    MonitorToJSON,
} from './';

/**
 * 
 * @export
 * @interface MonitorArray
 */
export interface MonitorArray {
    /**
     * 
     * @type {Array<Monitor>}
     * @memberof MonitorArray
     */
    monitors: Array<Monitor>;
}

export function MonitorArrayFromJSON(json: any): MonitorArray {
    return MonitorArrayFromJSONTyped(json, false);
}

export function MonitorArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'monitors': ((json['monitors'] as Array<any>).map(MonitorFromJSON)),
    };
}

export function MonitorArrayToJSON(value?: MonitorArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'monitors': ((value.monitors as Array<any>).map(MonitorToJSON)),
    };
}


