/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * What sort of system or entity the monitor will run a check on
 * @export
 * @enum {string}
 */
export enum MonitorType {
    Http = 'http',
    Process = 'process',
    Tcp = 'tcp',
    Redis = 'redis'
}

export function MonitorTypeFromJSON(json: any): MonitorType {
    return MonitorTypeFromJSONTyped(json, false);
}

export function MonitorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorType {
    return json as MonitorType;
}

export function MonitorTypeToJSON(value?: MonitorType | null): any {
    return value as any;
}

