/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    HttpMonitorBody,
    ProcessMonitorBody,
    TcpMonitorBody,
    HttpMonitorBodyFromJSONTyped,
    HttpMonitorBodyToJSON,
    ProcessMonitorBodyFromJSONTyped,
    ProcessMonitorBodyToJSON,
    TcpMonitorBodyFromJSONTyped,
    TcpMonitorBodyToJSON,
} from './';

/**
 * @type MonitorBody
 * 
 * @export
 */
export type MonitorBody = HttpMonitorBody | ProcessMonitorBody | TcpMonitorBody;

export function MonitorBodyFromJSON(json: any): MonitorBody {
    return MonitorBodyFromJSONTyped(json, false);
}

export function MonitorBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...HttpMonitorBodyFromJSONTyped(json, true), ...ProcessMonitorBodyFromJSONTyped(json, true), ...TcpMonitorBodyFromJSONTyped(json, true) };
}

export function MonitorBodyToJSON(value?: MonitorBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...HttpMonitorBodyToJSON(value), ...ProcessMonitorBodyToJSON(value), ...TcpMonitorBodyToJSON(value) };
}

