/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonitorStatusLogEntry
 */
export interface MonitorStatusLogEntry {
    /**
     * UTC UNIX timestamp in with fractional offset.
     * @type {Date}
     * @memberof MonitorStatusLogEntry
     */
    readonly timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof MonitorStatusLogEntry
     */
    value: string;
}

export function MonitorStatusLogEntryFromJSON(json: any): MonitorStatusLogEntry {
    return MonitorStatusLogEntryFromJSONTyped(json, false);
}

export function MonitorStatusLogEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorStatusLogEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': (new Date(json['timestamp'])),
        'value': json['value'],
    };
}

export function MonitorStatusLogEntryToJSON(value?: MonitorStatusLogEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}


