/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MonitorStatus,
    MonitorStatusFromJSON,
    MonitorStatusFromJSONTyped,
    MonitorStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface MonitorStatusArray
 */
export interface MonitorStatusArray {
    /**
     * 
     * @type {Array<MonitorStatus>}
     * @memberof MonitorStatusArray
     */
    statuses: Array<MonitorStatus>;
}

export function MonitorStatusArrayFromJSON(json: any): MonitorStatusArray {
    return MonitorStatusArrayFromJSONTyped(json, false);
}

export function MonitorStatusArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorStatusArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statuses': ((json['statuses'] as Array<any>).map(MonitorStatusFromJSON)),
    };
}

export function MonitorStatusArrayToJSON(value?: MonitorStatusArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statuses': ((value.statuses as Array<any>).map(MonitorStatusToJSON)),
    };
}


