/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MonitorStatusIndicator {
    Ok = 'ok',
    Down = 'down'
}

export function MonitorStatusIndicatorFromJSON(json: any): MonitorStatusIndicator {
    return MonitorStatusIndicatorFromJSONTyped(json, false);
}

export function MonitorStatusIndicatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorStatusIndicator {
    return json as MonitorStatusIndicator;
}

export function MonitorStatusIndicatorToJSON(value?: MonitorStatusIndicator | null): any {
    return value as any;
}

