/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * What sort of system or entity the monitor will run a check on
 * @export
 * @enum {string}
 */
export enum MonitorType {
    Http = 'http',
    Process = 'process',
    Tcp = 'tcp'
}

export function MonitorTypeFromJSON(json: any): MonitorType {
    return MonitorTypeFromJSONTyped(json, false);
}

export function MonitorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorType {
    return json as MonitorType;
}

export function MonitorTypeToJSON(value?: MonitorType | null): any {
    return value as any;
}

