/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonitorStatusResult
 */
export interface MonitorStatusResult {
    /**
     * 
     * @type {string}
     * @memberof MonitorStatusResult
     */
    expected: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorStatusResult
     */
    actual: string;
}

export function MonitorStatusResultFromJSON(json: any): MonitorStatusResult {
    return MonitorStatusResultFromJSONTyped(json, false);
}

export function MonitorStatusResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorStatusResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expected': json['expected'],
        'actual': json['actual'],
    };
}

export function MonitorStatusResultToJSON(value?: MonitorStatusResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expected': value.expected,
        'actual': value.actual,
    };
}


