/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MsTeamsAlertBody
 */
export interface MsTeamsAlertBody {
    /**
     * 
     * @type {string}
     * @memberof MsTeamsAlertBody
     */
    url?: string;
}

export function MsTeamsAlertBodyFromJSON(json: any): MsTeamsAlertBody {
    return MsTeamsAlertBodyFromJSONTyped(json, false);
}

export function MsTeamsAlertBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsTeamsAlertBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function MsTeamsAlertBodyToJSON(value?: MsTeamsAlertBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}


