/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agent,
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewAgent
 */
export interface NewAgent extends Agent {
    /**
     * 
     * @type {string}
     * @memberof NewAgent
     */
    readonly apiKey: string;
}

export function NewAgentFromJSON(json: any): NewAgent {
    return NewAgentFromJSONTyped(json, false);
}

export function NewAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAgent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...AgentFromJSONTyped(json, ignoreDiscriminator),
        'apiKey': json['apiKey'],
    };
}

export function NewAgentToJSON(value?: NewAgent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...AgentToJSON(value),
    };
}


