/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BoolExpr,
    BoolExprFromJSON,
    BoolExprFromJSONTyped,
    BoolExprToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotExpr
 */
export interface NotExpr {
    /**
     * 
     * @type {BoolExpr}
     * @memberof NotExpr
     */
    expr?: BoolExpr;
}

export function NotExprFromJSON(json: any): NotExpr {
    return NotExprFromJSONTyped(json, false);
}

export function NotExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotExpr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expr': !exists(json, 'expr') ? undefined : BoolExprFromJSON(json['expr']),
    };
}

export function NotExprToJSON(value?: NotExpr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expr': BoolExprToJSON(value.expr),
    };
}


