/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BoolExpr,
    BoolExprFromJSON,
    BoolExprFromJSONTyped,
    BoolExprToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrExpr
 */
export interface OrExpr {
    /**
     * 
     * @type {BoolExpr}
     * @memberof OrExpr
     */
    lhs: BoolExpr;
    /**
     * 
     * @type {BoolExpr}
     * @memberof OrExpr
     */
    rhs: BoolExpr;
}

export function OrExprFromJSON(json: any): OrExpr {
    return OrExprFromJSONTyped(json, false);
}

export function OrExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrExpr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lhs': BoolExprFromJSON(json['lhs']),
        'rhs': BoolExprFromJSON(json['rhs']),
    };
}

export function OrExprToJSON(value?: OrExpr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lhs': BoolExprToJSON(value.lhs),
        'rhs': BoolExprToJSON(value.rhs),
    };
}


