/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Plan,
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlanArray
 */
export interface PlanArray {
    /**
     * 
     * @type {Array<Plan>}
     * @memberof PlanArray
     */
    plans: Array<Plan>;
}

export function PlanArrayFromJSON(json: any): PlanArray {
    return PlanArrayFromJSONTyped(json, false);
}

export function PlanArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plans': ((json['plans'] as Array<any>).map(PlanFromJSON)),
    };
}

export function PlanArrayToJSON(value?: PlanArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plans': ((value.plans as Array<any>).map(PlanToJSON)),
    };
}


