/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductEntity {
    Monitor = 'monitor',
    Status = 'status',
    Alert = 'alert',
    Agent = 'agent',
    User = 'user',
    Session = 'session'
}

export function ProductEntityFromJSON(json: any): ProductEntity {
    return ProductEntityFromJSONTyped(json, false);
}

export function ProductEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductEntity {
    return json as ProductEntity;
}

export function ProductEntityToJSON(value?: ProductEntity | null): any {
    return value as any;
}

