/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationConfirmation
 */
export interface RegistrationConfirmation {
    /**
     * 
     * @type {string}
     * @memberof RegistrationConfirmation
     */
    readonly id: string;
    /**
     * A secret string between the client and the API. A valid confirmation code is proof the user owns the email address
     * @type {string}
     * @memberof RegistrationConfirmation
     */
    confirmationCode: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationConfirmation
     */
    emailAddress?: string;
}

export function RegistrationConfirmationFromJSON(json: any): RegistrationConfirmation {
    return RegistrationConfirmationFromJSONTyped(json, false);
}

export function RegistrationConfirmationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationConfirmation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'confirmationCode': json['confirmationCode'],
        'emailAddress': !exists(json, 'emailAddress') ? undefined : json['emailAddress'],
    };
}

export function RegistrationConfirmationToJSON(value?: RegistrationConfirmation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmationCode': value.confirmationCode,
        'emailAddress': value.emailAddress,
    };
}


