/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ErrorCode,
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResponseError
 */
export interface ResponseError {
    /**
     * 
     * @type {ErrorCode}
     * @memberof ResponseError
     */
    errorCode: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof ResponseError
     */
    errorMessage: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseError
     */
    userErrorMessage: string;
}

export function ResponseErrorFromJSON(json: any): ResponseError {
    return ResponseErrorFromJSONTyped(json, false);
}

export function ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': ErrorCodeFromJSON(json['errorCode']),
        'errorMessage': json['errorMessage'],
        'userErrorMessage': json['userErrorMessage'],
    };
}

export function ResponseErrorToJSON(value?: ResponseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': ErrorCodeToJSON(value.errorCode),
        'errorMessage': value.errorMessage,
        'userErrorMessage': value.userErrorMessage,
    };
}


