/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Server info and status about open connections
 * @export
 * @interface ServerInfo
 */
export interface ServerInfo {
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    vcsRef?: string;
    /**
     * 
     * @type {number}
     * @memberof ServerInfo
     */
    processMemoryBytes: number;
    /**
     * 
     * @type {number}
     * @memberof ServerInfo
     */
    openInwardConnections: number;
}

export function ServerInfoFromJSON(json: any): ServerInfo {
    return ServerInfoFromJSONTyped(json, false);
}

export function ServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vcsRef': !exists(json, 'vcsRef') ? undefined : json['vcsRef'],
        'processMemoryBytes': json['processMemoryBytes'],
        'openInwardConnections': json['openInwardConnections'],
    };
}

export function ServerInfoToJSON(value?: ServerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vcsRef': value.vcsRef,
        'processMemoryBytes': value.processMemoryBytes,
        'openInwardConnections': value.openInwardConnections,
    };
}


