/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChargeType,
    ChargeTypeFromJSON,
    ChargeTypeFromJSONTyped,
    ChargeTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    readonly organisationId?: string;
    /**
     * UTC UNIX timestamp in with fractional offset.
     * @type {Date}
     * @memberof Subscription
     */
    readonly startedAt?: Date;
    /**
     * UTC UNIX timestamp in with fractional offset.
     * @type {Date}
     * @memberof Subscription
     */
    readonly stoppedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    planId: string;
    /**
     * 
     * @type {ChargeType}
     * @memberof Subscription
     */
    chargeType: ChargeType;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'organisationId': !exists(json, 'organisationId') ? undefined : json['organisationId'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'stoppedAt': !exists(json, 'stoppedAt') ? undefined : (new Date(json['stoppedAt'])),
        'planId': json['planId'],
        'chargeType': ChargeTypeFromJSON(json['chargeType']),
    };
}

export function SubscriptionToJSON(value?: Subscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'planId': value.planId,
        'chargeType': ChargeTypeToJSON(value.chargeType),
    };
}


