/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Subscription,
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface SubscriptionContainer
 */
export interface SubscriptionContainer {
    /**
     * 
     * @type {Subscription}
     * @memberof SubscriptionContainer
     */
    subscription?: Subscription;
}

export function SubscriptionContainerFromJSON(json: any): SubscriptionContainer {
    return SubscriptionContainerFromJSONTyped(json, false);
}

export function SubscriptionContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionContainer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subscription': !exists(json, 'subscription') ? undefined : SubscriptionFromJSON(json['subscription']),
    };
}

export function SubscriptionContainerToJSON(value?: SubscriptionContainer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subscription': SubscriptionToJSON(value.subscription),
    };
}


