/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Controls whether or not STARTTLS will be used.
 * @export
 * @enum {string}
 */
export enum TlsMode {
    None = 'none',
    Tls = 'tls',
    Starttls = 'starttls'
}

export function TlsModeFromJSON(json: any): TlsMode {
    return TlsModeFromJSONTyped(json, false);
}

export function TlsModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TlsMode {
    return json as TlsMode;
}

export function TlsModeToJSON(value?: TlsMode | null): any {
    return value as any;
}

