/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TransactionCode {
    SubscriptionCredit = 'subscription_credit',
    SubscriptionCharge = 'subscription_charge',
    SubscriptionRefund = 'subscription_refund',
    SubscriptionCorrection = 'subscription_correction',
    SubscriptionAdjustment = 'subscription_adjustment',
    OpeningBalance = 'opening_balance'
}

export function TransactionCodeFromJSON(json: any): TransactionCode {
    return TransactionCodeFromJSONTyped(json, false);
}

export function TransactionCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionCode {
    return json as TransactionCode;
}

export function TransactionCodeToJSON(value?: TransactionCode | null): any {
    return value as any;
}

