/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Money,
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    TransactionCode,
    TransactionCodeFromJSON,
    TransactionCodeFromJSONTyped,
    TransactionCodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    readonly id: string;
    /**
     * UTC UNIX timestamp in with fractional offset.
     * @type {Date}
     * @memberof Transaction
     */
    readonly timestamp: Date;
    /**
     * 
     * @type {Money}
     * @memberof Transaction
     */
    amount: Money;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    readonly description: string;
    /**
     * 
     * @type {TransactionCode}
     * @memberof Transaction
     */
    code: TransactionCode;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': (new Date(json['timestamp'])),
        'amount': MoneyFromJSON(json['amount']),
        'description': json['description'],
        'code': TransactionCodeFromJSON(json['code']),
    };
}

export function TransactionToJSON(value?: Transaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': MoneyToJSON(value.amount),
        'code': TransactionCodeToJSON(value.code),
    };
}


