/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Balance,
    BalanceFromJSON,
    BalanceFromJSONTyped,
    BalanceToJSON,
    Transaction,
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionList
 */
export interface TransactionList {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof TransactionList
     */
    transactions?: Array<Transaction>;
    /**
     * 
     * @type {Balance}
     * @memberof TransactionList
     */
    openingBalance?: Balance;
    /**
     * 
     * @type {Balance}
     * @memberof TransactionList
     */
    closingBalance?: Balance;
}

export function TransactionListFromJSON(json: any): TransactionList {
    return TransactionListFromJSONTyped(json, false);
}

export function TransactionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactions': !exists(json, 'transactions') ? undefined : ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
        'openingBalance': !exists(json, 'openingBalance') ? undefined : BalanceFromJSON(json['openingBalance']),
        'closingBalance': !exists(json, 'closingBalance') ? undefined : BalanceFromJSON(json['closingBalance']),
    };
}

export function TransactionListToJSON(value?: TransactionList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactions': value.transactions === undefined ? undefined : ((value.transactions as Array<any>).map(TransactionToJSON)),
        'openingBalance': BalanceToJSON(value.openingBalance),
        'closingBalance': BalanceToJSON(value.closingBalance),
    };
}


