/* tslint:disable */
/* eslint-disable */
/**
 * Open Monitors
 * This is the Open Monitors API. All operations that a user or an agent would want to complete, including signing up, are listed here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openmonitors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TransactionCode {
    SubscriptionCredit = 'subscription_credit',
    SubscriptionCharge = 'subscription_charge',
    SubscriptionRefund = 'subscription_refund',
    SubscriptionCorrection = 'subscription_correction',
    SubscriptionAdjustment = 'subscription_adjustment',
    OpeningBalance = 'opening_balance'
}

export function TransactionCodeFromJSON(json: any): TransactionCode {
    return TransactionCodeFromJSONTyped(json, false);
}

export function TransactionCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionCode {
    return json as TransactionCode;
}

export function TransactionCodeToJSON(value?: TransactionCode | null): any {
    return value as any;
}

