/* tslint:disable */
/* eslint-disable */
/**
 * Schnooty API
 * This is the Schnooty API. It is used by both our agent and web application to manage your monitors, agents, alerts, account settings and everything else
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@schnooty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HttpHeader,
    HttpHeaderFromJSON,
    HttpHeaderFromJSONTyped,
    HttpHeaderToJSON,
} from './';

/**
 * 
 * @export
 * @interface WebhookAlertBody
 */
export interface WebhookAlertBody {
    /**
     * 
     * @type {string}
     * @memberof WebhookAlertBody
     */
    url?: string;
    /**
     * 
     * @type {Array<HttpHeader>}
     * @memberof WebhookAlertBody
     */
    headers?: Array<HttpHeader>;
}

export function WebhookAlertBodyFromJSON(json: any): WebhookAlertBody {
    return WebhookAlertBodyFromJSONTyped(json, false);
}

export function WebhookAlertBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAlertBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'headers': !exists(json, 'headers') ? undefined : ((json['headers'] as Array<any>).map(HttpHeaderFromJSON)),
    };
}

export function WebhookAlertBodyToJSON(value?: WebhookAlertBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'headers': value.headers === undefined ? undefined : ((value.headers as Array<any>).map(HttpHeaderToJSON)),
    };
}


